SUMM_INPUT = 'Введите сумму кредита'
PERCENT_INPUT = 'Введите процентную ставку'
PERIOD_INPUT = 'Введите срок кредитования (в годах)'
PAYMENT_PRINT = 'Платёж'
TOTAL_LOAN_AMOUNT = 'Общая сумма кредита составит'
